<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="spdmeasuringpoint" nsURI="http://palladiosimulator.org/PCM/SPDMeasuringPoint/1.0"
    nsPrefix="spdmeasuringpoint">
  <eClassifiers xsi:type="ecore:EClass" name="ElasticInfrastructureMeasuringPoint"
      eSuperTypes="../../org.palladiosimulator.edp2/model/EDP2.ecore#//measuringpoint/MeasuringPoint #//ElasticInfrastructureReference"/>
  <eClassifiers xsi:type="ecore:EClass" name="ServiceGroupMeasuringPoint" eSuperTypes="../../org.palladiosimulator.edp2/model/EDP2.ecore#//measuringpoint/MeasuringPoint #//ServiceGroupReference"/>
  <eClassifiers xsi:type="ecore:EClass" name="CompetingConsumerGroupMeasuringPoint"
      eSuperTypes="../../org.palladiosimulator.edp2/model/EDP2.ecore#//measuringpoint/MeasuringPoint #//CompetingConsumerGroupReference"/>
  <eClassifiers xsi:type="ecore:EClass" name="ServiceGroupReference" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="serviceGroup" lowerBound="1"
        eType="ecore:EClass ../../org.palladiosimulator.spd/model/SPD.ecore#//targets/ServiceGroup"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ElasticInfrastructureReference" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="elasticInfrastructure"
        lowerBound="1" eType="ecore:EClass ../../org.palladiosimulator.spd/model/SPD.ecore#//targets/ElasticInfrastructure"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CompetingConsumerGroupReference" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="competingConsumerGroup"
        lowerBound="1" eType="ecore:EClass ../../org.palladiosimulator.spd/model/SPD.ecore#//targets/CompetingConsumersGroup"/>
  </eClassifiers>
</ecore:EPackage>
