<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="semanticspd" nsURI="http://palladiosimulator.org/ScalingPolicyDefinitionSemantic/1.0"
    nsPrefix="semanticspd">
  <eClassifiers xsi:type="ecore:EClass" name="Configuration">
    <eStructuralFeatures xsi:type="ecore:EReference" name="spd" eType="ecore:EClass ../../org.palladiosimulator.spd/model/SPD.ecore#//SPD"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="enactedPolicy" eType="ecore:EClass ../../org.palladiosimulator.spd/model/SPD.ecore#//ScalingPolicy"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetCfgs" upperBound="-1"
        eType="#//TargetGroupCfg" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="allocation" eType="ecore:EClass ../../org.palladiosimulator.pcm/model/pcm.ecore#//allocation/Allocation"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="system" eType="ecore:EClass ../../org.palladiosimulator.pcm/model/pcm.ecore#//system/System"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="resourceEnvironment" eType="ecore:EClass ../../org.palladiosimulator.pcm/model/pcm.ecore#//resourceenvironment/ResourceEnvironment"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="repository" eType="ecore:EClass ../../org.palladiosimulator.pcm/model/pcm.ecore#//repository/Repository"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TargetGroupCfg" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="enactedPolicies" upperBound="-1"
        eType="ecore:EClass ../../org.palladiosimulator.spd/model/SPD.ecore#//ScalingPolicy"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ElasticInfrastructureCfg" eSuperTypes="#//TargetGroupCfg">
    <eStructuralFeatures xsi:type="ecore:EReference" name="unit" eType="ecore:EClass ../../org.palladiosimulator.pcm/model/pcm.ecore#//resourceenvironment/ResourceContainer"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elements" lowerBound="1"
        upperBound="-1" eType="ecore:EClass ../../org.palladiosimulator.pcm/model/pcm.ecore#//resourceenvironment/ResourceContainer"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="linkingResource" eType="ecore:EClass ../../org.palladiosimulator.pcm/model/pcm.ecore#//resourceenvironment/LinkingResource"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="resourceEnvironment" eType="ecore:EClass ../../org.palladiosimulator.pcm/model/pcm.ecore#//resourceenvironment/ResourceEnvironment"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ServiceGroupCfg" eSuperTypes="#//TargetGroupCfg">
    <eStructuralFeatures xsi:type="ecore:EReference" name="unit" eType="ecore:EClass ../../org.palladiosimulator.pcm/model/pcm.ecore#//core/composition/AssemblyContext"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elements" lowerBound="1"
        upperBound="-1" eType="ecore:EClass ../../org.palladiosimulator.pcm/model/pcm.ecore#//core/composition/AssemblyContext"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="loadBalancingAssembly"
        eType="ecore:EClass ../../org.palladiosimulator.pcm/model/pcm.ecore#//core/composition/AssemblyContext"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CompetingConsumersGroupCfg" eSuperTypes="#//TargetGroupCfg">
    <eStructuralFeatures xsi:type="ecore:EReference" name="unit" eType="ecore:EClass ../../org.palladiosimulator.pcm/model/pcm.ecore#//core/composition/AssemblyContext"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elements" lowerBound="1"
        upperBound="-1" eType="ecore:EClass ../../org.palladiosimulator.pcm/model/pcm.ecore#//core/composition/AssemblyContext"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="brokerAssembly" eType="ecore:EClass ../../org.palladiosimulator.pcm/model/pcm.ecore#//core/composition/AssemblyContext"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="unitQueues" lowerBound="1"
        upperBound="-1" eType="#//Queue" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Queue">
    <eStructuralFeatures xsi:type="ecore:EReference" name="passiveResourceQueueMessages"
        eType="ecore:EClass ../../org.palladiosimulator.pcm/model/pcm.ecore#//repository/PassiveResource"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="usageScenarioForConsumption"
        eType="ecore:EClass ../../org.palladiosimulator.pcm/model/pcm.ecore#//usagemodel/UsageScenario"/>
  </eClassifiers>
</ecore:EPackage>
