<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="spd" nsURI="spd" nsPrefix="spd">
  <eAnnotations source="http://www.eclipse.org/OCL/Import">
    <details key="ecore" value="http://www.eclipse.org/emf/2002/Ecore"/>
  </eAnnotations>
  <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
    <details key="invocationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    <details key="settingDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    <details key="validationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="ScalingPolicy">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="policyNameInvariant"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="policyNameInvariant" value="policyName &lt;>''"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetgroup" lowerBound="1"
        eType="#//TargetGroup"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="adjustmenttype" lowerBound="1"
        eType="#//AdjustmentType" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="scalingtrigger" lowerBound="1"
        eType="#//ScalingTrigger" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="policyconstraint" upperBound="-1"
        eType="#//PolicyConstraint" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="policyName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SPD">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="nameInvariant"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="nameInvariant" value="name &lt;>''"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="scalingpolicy" lowerBound="1"
        upperBound="-1" eType="#//ScalingPolicy" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TargetGroup" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="AdjustmentType" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="ScalingTrigger" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="PolicyConstraint" abstract="true"/>
  <eSubpackages name="targetgroup" nsURI="targetgroup" nsPrefix="targetgroup">
    <eClassifiers xsi:type="ecore:EClass" name="TargetGroup" eSuperTypes="#//TargetGroup">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="PCM_ResourceEnvironment"
          eType="#//palladio/PCMResourceEnvironment"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="adjustmenttype" nsURI="adjustmenttype" nsPrefix="adjustmenttype">
    <eClassifiers xsi:type="ecore:EClass" name="AdjustmentType" abstract="true" eSuperTypes="#//AdjustmentType"/>
    <eClassifiers xsi:type="ecore:EClass" name="RelativeAdjustment" eSuperTypes="#//adjustmenttype/AdjustmentType">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="percentageValue" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
          defaultValueLiteral="0.0"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="minAdjustmentValue" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" defaultValueLiteral="0"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="AbsoluteAdjustment" eSuperTypes="#//adjustmenttype/AdjustmentType">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="goalValue" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" defaultValueLiteral="0"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="StepAdjustment" eSuperTypes="#//adjustmenttype/AdjustmentType">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="stepValue" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" defaultValueLiteral="0"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="policyconstraint" nsURI="policyconstraint" nsPrefix="policyconstraint">
    <eClassifiers xsi:type="ecore:EClass" name="PolicyConstraint" abstract="true"
        eSuperTypes="#//PolicyConstraint"/>
    <eClassifiers xsi:type="ecore:EClass" name="TimeBasedConstraint" abstract="true"
        eSuperTypes="#//policyconstraint/PolicyConstraint"/>
    <eClassifiers xsi:type="ecore:EClass" name="GroupSizeConstraint" eSuperTypes="#//policyconstraint/PolicyConstraint">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="minSize" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxSize" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="IntervallConstraint" eSuperTypes="#//policyconstraint/TimeBasedConstraint">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="offset" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="intervallDuration" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="CooldownConstraint" eSuperTypes="#//policyconstraint/TimeBasedConstraint">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="cooldownTime" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxScalingOperations"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="scalingtrigger" nsURI="scalingtrigger" nsPrefix="scalingtrigger">
    <eClassifiers xsi:type="ecore:EClass" name="ScalingTrigger" abstract="true" eSuperTypes="#//ScalingTrigger"/>
    <eClassifiers xsi:type="ecore:EClass" name="ThresholdBasedTrigger" abstract="true"
        eSuperTypes="#//scalingtrigger/ScalingTrigger">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="thresholdDirection" eType="#//scalingtrigger/THRESHOLDDIRECTION"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="threshold" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
          defaultValueLiteral="0.0"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="violationWindow" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="CPUUtilizationTrigger" eSuperTypes="#//scalingtrigger/ProcessingResourceUtilizationBasedTrigger"/>
    <eClassifiers xsi:type="ecore:EClass" name="RAMUtilizationTrigger" eSuperTypes="#//scalingtrigger/ProcessingResourceUtilizationBasedTrigger"/>
    <eClassifiers xsi:type="ecore:EClass" name="HDDUtilizationTrigger" eSuperTypes="#//scalingtrigger/ProcessingResourceUtilizationBasedTrigger">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="usageType" eType="#//scalingtrigger/HDDUSAGETYPE"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TimeBasedTrigger" abstract="true"
        eSuperTypes="#//scalingtrigger/ThresholdBasedTrigger"/>
    <eClassifiers xsi:type="ecore:EClass" name="PointInTimeTrigger" eSuperTypes="#//scalingtrigger/ScalingTrigger">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="pointInTime" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="IdleTimeTrigger" eSuperTypes="#//scalingtrigger/TimeBasedTrigger">
      <eStructuralFeatures xsi:type="ecore:EReference" name="resourceContainer" upperBound="-1"
          eType="#//palladio/PCMResourceContainer"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="AGGREGATIONMETHOD">
      <eLiterals name="AVERAGE"/>
      <eLiterals name="MAX" value="1"/>
      <eLiterals name="MIN" value="2"/>
      <eLiterals name="MEDIAN" value="3"/>
      <eLiterals name="SUM" value="4"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TaskCountTrigger" eSuperTypes="#//scalingtrigger/ThresholdBasedTrigger">
      <eStructuralFeatures xsi:type="ecore:EReference" name="resourceContainer" upperBound="-1"
          eType="#//palladio/PCMResourceContainer"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="processingResourceAggregation"
          eType="#//scalingtrigger/AGGREGATIONMETHOD"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="resourceContainerAggregation"
          eType="#//scalingtrigger/AGGREGATIONMETHOD"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="HDDUSAGETYPE">
      <eLiterals name="READ"/>
      <eLiterals name="WRITE" value="1"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="NetworkUtilizationTrigger" eSuperTypes="#//scalingtrigger/ResourceUtilizationBasedTrigger">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="usageType" eType="#//scalingtrigger/NETWORKUSAGETYPE"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="linkingResource" upperBound="-1"
          eType="#//palladio/PCMLinkingResource"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="NETWORKUSAGETYPE">
      <eLiterals name="SEND"/>
      <eLiterals name="RECEIVE" value="1"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="THRESHOLDDIRECTION">
      <eLiterals name="EXCEDEED"/>
      <eLiterals name="UNDERCUT" value="1"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ResponseTimeTrigger" eSuperTypes="#//scalingtrigger/TimeBasedTrigger">
      <eStructuralFeatures xsi:type="ecore:EReference" name="operationSignature" upperBound="-1"
          eType="#//palladio/PCMOperationSignature"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ResourceUtilizationBasedTrigger" abstract="true"
        eSuperTypes="#//scalingtrigger/ThresholdBasedTrigger">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="processingResourceAggregation"
          eType="#//scalingtrigger/AGGREGATIONMETHOD"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="resourceContainerAggregation"
          eType="#//scalingtrigger/AGGREGATIONMETHOD"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ProcessingResourceUtilizationBasedTrigger"
        abstract="true" eSuperTypes="#//scalingtrigger/ResourceUtilizationBasedTrigger"/>
  </eSubpackages>
  <eSubpackages name="palladio" nsURI="palladio" nsPrefix="palladio">
    <eClassifiers xsi:type="ecore:EClass" name="PCMResourceEnvironment">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PCMResourceContainer">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PCMLinkingResource">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PCMOperationSignature">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </eSubpackages>
</ecore:EPackage>
